FROM node:22-alpine AS base
WORKDIR /app
COPY ./backend/package*.json ./

FROM base AS development
WORKDIR /code
COPY ./backend/package*.json ./
RUN npm install -g nodemon ts-node
RUN npm install
RUN mkdir app
COPY ./backend/config.cfg ./app
COPY ./backend .
EXPOSE 3001
CMD ["nodemon", "--watch", "scr", "--ext", "ts", "--exec", "ts-node", "scr/index.ts"]

FROM base AS builder
RUN npm install
COPY ./backend .
RUN npm run build

FROM node:22-alpine AS production
WORKDIR /app
COPY ./backend/package*.json ./
RUN npm install --omit=dev
COPY --from=builder /app/dist ./dist
EXPOSE 3001
CMD ["node", "dist/index.js"]