FROM node:22-alpine AS base
WORKDIR /app
COPY ./frontend/package*.json ./

FROM base AS development
RUN npm install -g @angular/cli
RUN npm ci --legacy-peer-deps
COPY ./frontend .
EXPOSE 4200
CMD ["npx", "ng", "serve", "--host", "0.0.0.0", "--poll", "500"]

FROM base AS builder
RUN npm ci --legacy-peer-deps
COPY ./frontend .
RUN npx ng build --configuration production

FROM nginx:1.25-alpine AS production
COPY --from=builder /app/dist/demo1 /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
