FROM node:22-alpine AS base
WORKDIR /app
COPY ./backend/package*.json ./

FROM base AS development
WORKDIR /code
RUN npm install -g nodemon
RUN npm install dotenv
RUN npm install
RUN mkdir app
COPY ./backend/config.cfg ./app
COPY ./backend .
EXPOSE 3001
CMD ["npm", "run", "dev"]

FROM base AS builder
RUN npm install
COPY ./backend .
RUN npm run build

FROM node:22-alpine AS production
WORKDIR /app
COPY package*.json ./
RUN npm install --omit=dev
COPY --from=builder /app/dist ./dist
EXPOSE 3000
CMD ["node", "dist/main"]
